version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install architect
          command: |
            wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
            chmod +x ./architect
            ./architect version

      - run:
          name: architect build
          command: ./architect build

      - deploy:
          name: architect deploy (master only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./architect deploy
            fi
