apiVersion: v1
kind: ConfigMap
metadata:
  name: draughtsman
  namespace: draughtsman
data:
  config.yaml: |
    service:
      deployer:
        provider: {{ .Values.Installation.V1.Provider.Kind }}
    server:
      listen:
        address: 'http://0.0.0.0:8000'
