apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      volumes:
      - name: configmap
        configMap:
          name: draughtsman
      - name: secret
        secret:
          secretName: draughtsman
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: {{ .Values.name }}
        image: quay.io/giantswarm/draughtsman:[[ .SHA ]]
        args:
        - "daemon"
        - "--config.dirs=/var/run/draughtsman/configmap/"
        - "--config.dirs=/var/run/draughtsman/secret/"
        - "--config.files=config"
        - "--config.files=secret"
        volumeMounts:
        - name: configmap
          mountPath: /var/run/draughtsman/configmap/
          readOnly: true
        - name: secret
          mountPath: /var/run/draughtsman/secret/
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "5"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 100m
            memory: 150Mi
      imagePullSecrets:
      - name: draughtsman-pull-secret
